# Generated by Django 5.0.7 on 2024-07-12 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionDetails',
            fields=[
                ('auction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auction_date', models.DateField(blank=True)),
                ('auction_start_time', models.TimeField(blank=True)),
                ('auction_end_time', models.TimeField(blank=True)),
                ('increment_amount', models.FloatField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='seller.productinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_type', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=10)),
                ('bidder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticBidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bid_amount', models.FloatField(blank=True)),
                ('inc_amount', models.FloatField(blank=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_autobids', to='auction.auctiondetails')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autobids', to='auction.bidders')),
            ],
        ),
        migrations.CreateModel(
            name='AllBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allauctionbids', to='auction.auctiondetails')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allbids', to='auction.bidders')),
            ],
        ),
        migrations.CreateModel(
            name='ClosingBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_bid_amount', models.FloatField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_auctions', to='auction.auctiondetails')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_Bids', to='auction.bidders')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAuctions',
            fields=[
                ('current_auction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_auction', to='auction.auctiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctionbids', to='auction.auctiondetails')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentbids', to='auction.bidders')),
            ],
        ),
    ]
