<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-07-19 12:50
=======
# Generated by Django 5.0.7 on 2024-07-29 17:09
>>>>>>> shivanik

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinformation',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.productcategory'),
        ),
    ]
